// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2gQjgUllPlhU-1GKthMcrArdShT2AIPU',
    appId: '1:38302719013:web:23e7dc410514ae43d573cc',
    messagingSenderId: '38302719013',
    projectId: 'mifik-83723',
    authDomain: 'mifik-83723.firebaseapp.com',
    storageBucket: 'mifik-83723.appspot.com',
    measurementId: 'G-V13CR730JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSPZjX15E_IRgdzaSvtqMbT8m0uogqDQQ',
    appId: '1:38302719013:android:f50ffdf1e7bbc55ad573cc',
    messagingSenderId: '38302719013',
    projectId: 'mifik-83723',
    storageBucket: 'mifik-83723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfEBYpASgyX5bWltIHOq1qjFuJQXwM8qg',
    appId: '1:38302719013:ios:6c89c4d61110c555d573cc',
    messagingSenderId: '38302719013',
    projectId: 'mifik-83723',
    storageBucket: 'mifik-83723.appspot.com',
    iosClientId: '38302719013-i50pbvolrpdb4hkc3m0r4jd8k8ctgc7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.miFik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfEBYpASgyX5bWltIHOq1qjFuJQXwM8qg',
    appId: '1:38302719013:ios:6c89c4d61110c555d573cc',
    messagingSenderId: '38302719013',
    projectId: 'mifik-83723',
    storageBucket: 'mifik-83723.appspot.com',
    iosClientId: '38302719013-i50pbvolrpdb4hkc3m0r4jd8k8ctgc7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.miFik',
  );
}
